---

nats:
  auth:
    enabled: false
  debug:
    enabled: true
  replicaCount: 3

micro:
  srv1: &srv1
    image:
      repository: sk4zuzu/topspin
      tag: latest
      pullPolicy: Always
    replicaCount: 3
  srv2:
    <<: *srv1
  api:
    <<: *srv1
    environment:
      GIN_MODE: release

service:
  type: NodePort
  port: 80

ingress:
  enabled: false

# vim:ts=2:sw=2:et:syn=yaml:
