
nats:
  auth:
    enabled: false
  debug:
    enabled: true
  replicaCount: 3

micro:
  srv1:
    image:
      repository: sk4zuzu/topspin
      tag: latest
      pullPolicy: Always
    replicaCount: 3
  srv2:
    image:
      repository: sk4zuzu/topspin
      tag: latest
      pullPolicy: Always
    replicaCount: 3
  api:
    environment:
      GIN_MODE: release
    image:
      repository: sk4zuzu/topspin
      tag: latest
      pullPolicy: Always
    replicaCount: 3

service:
  type: NodePort
  nodePort: 32767
  port: 8080

ingress:
  enabled: false
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: sk4zuzu-eu
  path:
  hosts:
    - lel.sk4zuzu.eu

# vim:ts=2:sw=2:et:syn=yaml:
